Main.factory('AuthInterceptor', AuthInterceptor);
Main.factory('Auth', Auth);
Main.factory('friendsFactory', friendsFactory);
Main.factory('findFriendsFactory', findFriendsFactory);
Main.factory('rewardsFactory', rewardsFactory);
Main.factory('coordFactory', coordFactory);
Main.factory('calculateDistanceFactory', calculateDistanceFactory);
Main.factory('tripFactory', tripFactory);
Main.factory('profileFactory', profileFactory);